### ISSUE TITLE
Export function not clickable when target group selected

### ISSUE THREAD

**Issue by bdeclerc** [openfed/AccessibilityCheck#12]
If you use "show results for" to filter the report, the "export" link moves outside the box and becomes unreachable.

**Comment by stefanruijsenaars** [comment]
Removed the counters as we run out of space otherwise (and the counts are viewable by clicking the home button)

Before:

<img width="295" alt="Screen Shot 2019-11-23 at 00 30 04" src="https://user-images.githubusercontent.com/4950254/69469599-9a61c200-0d89-11ea-9bb1-96086fa20e3e.png">


After:

<img width="312" alt="Screen Shot 2019-11-23 at 00 36 31" src="https://user-images.githubusercontent.com/4950254/69469605-a057a300-0d89-11ea-8687-3100c5ea5e5f.png">

**Comment by stefanruijsenaars** [comment]
Fixed in https://github.com/openfed/AccessibilityCheck/commit/9cd845fe033a87723c9657291203cf0ceee4c971
