### ISSUE TITLE
What does this fork provide?

### ISSUE THREAD

**Issue by mgifford** [openfed/AccessibilityCheck#26]
This is a fork of HTML_CodeSniffer but how is it different?

Does it do site-wide scans, or is that just through integration with other tools? 

Mostly, why would I use this rather than the original? Or for that matter a tool like one of these built on axe: 
- https://github.com/GovTechSG/purple-hats
- https://github.com/MSU-NatSci/DomainAccessibilityAudit

**Comment by bdeclerc** [comment]
@mgifford it was created as a branch in part for implementing things at our own pace, like the translations to NL/FR, the WCAG 2.1 criteria checks and branding the tool with our own organisation name - rather than being dependent on someone else for those - most of our changes/fixes have been provided back upstream into HTML_CodeSniffer. We also include an explicit "skip iframes" option to avoid reports being too confusing when things like twitter-integration are present.

We're also using it as the engine behind our site-wide scan solution (which you can find in http://github.com/openfed/AccessibilityCheckServer )

I don't think someone other than us (FPS BOSA) really needs to use this rather than the original, except perhaps in situations where one of our already implemented changes is something you'd really already want to be using.

Axe is great and we use it frequently, but it's good to have multiple tools available for this kind of work, we've even forked this one further in a project where we're trying to integrate AI-based checks for certain hard-to-automate criteria-validations, though that project has an important server-component also.

**Comment by mgifford** [comment]
I think I am confused about what Openfed is or for that matter what BOSA is. Wait, Google - 
Federal Public Service Policy and Support (FPS BOSA)...  A link to that somewhere would be useful. 

I agree about trying to use different engines. axe, alfa, equal access, html codesniffer, whatever...  They are are somewhat different. 

Interesting about the use of it for checking branding though.  That could be useful to others.

I'm definitely interested in how you are building AI checks. Only folks I've known who I am hopeful have done this well are  https://www.evinced.com 

I'm looking for approaches to improve accessibility via open source tools. Curious if there is more to add here.  

Worth checking out:
https://github.com/MSU-NatSci/DomainAccessibilityAudit
https://github.com/GovTechSG/purple-hats
